import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
import { DatabaseSync } from 'node:sqlite';
import { _electron as electron, expect } from '@playwright/test';

const executablePath = fileURLToPath(new URL('../../../dist/mac/知境·Knowra-darwin-arm64/知境·Knowra.app/Contents/MacOS/Knowra', import.meta.url));
test('打包应用独立启动，隔离资料库正文在立即退出后落盘并可重启', { timeout: 60000 }, async t => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'knowra-mac-smoke-'));
  let app;
  t.after(async () => { if (app) await app.close().catch(() => {}); fs.rmSync(directory, { recursive: true, force: true }); });
  const launch = async () => electron.launch({ executablePath, env: { ...process.env, KNOWRA_DESKTOP_SMOKE_DIR: directory }, timeout: 20000 });
  app = await launch();
  let page = await app.firstWindow();
  await page.waitForLoadState('domcontentloaded');
  await expect.poll(() => fs.existsSync(path.join(directory, 'ready.json'))).toBe(true);
  t.diagnostic(JSON.stringify(JSON.parse(fs.readFileSync(path.join(directory, 'ready.json')))));
  const result = await page.evaluate(async () => {
    const space = (await (await fetch('/api/knowledge/spaces/default', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' })).json()).data;
    return (await (await fetch('/api/knowledge/notes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ spaceId: space.id, title: '打包工程检查', rawMarkdown: '原文' }) })).json()).data;
  });
  assert(result.id);
  await page.reload();
  await page.getByRole('button', { name: '打开 打包工程检查', exact: true }).click();
  const editor = page.locator('.ProseMirror');
  await expect(editor).toContainText('原文');
  await editor.click();
  await page.keyboard.press('ControlOrMeta+End');
  await page.keyboard.insertText(' 退出前未等防抖的中文');
  const closed = app.waitForEvent('close');
  await app.evaluate(({ app: nativeApp }) => { nativeApp.quit(); });
  await closed;
  app = null;
  const db = new DatabaseSync(path.join(directory, 'offline/local.sqlite'), { readOnly: true });
  const row = db.prepare("SELECT payload FROM entities WHERE collection = 'notes' AND id = ?").get(result.id);
  assert(JSON.parse(row.payload).rawMarkdown.includes('退出前未等防抖的中文'));
  db.close();
  app = await launch();
  page = await app.firstWindow();
  await page.waitForLoadState('domcontentloaded');
  await page.goto(`${new URL(page.url()).origin}/#/materials/notes/${result.id}`);
  await expect(page.locator('.ProseMirror')).toContainText('退出前未等防抖的中文');
  assert.equal(await page.evaluate(() => typeof window.require), 'undefined');
  const finalClosed = app.waitForEvent('close');
  await app.evaluate(({ app: nativeApp }) => { nativeApp.quit(); });
  await finalClosed; app = null;
});
