import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { test } from 'node:test';
import { importJsonSnapshot } from '../src/snapshot-migration.mjs';
import { createNote, openWorkspace, temporaryDirectory } from './helpers.mjs';
import { createAppContext } from '../../api/src/app.factory.js';

test('JSON 快照迁移保留正文、附件与 ID，迁移失败不发布目标，原快照不变', t => {
  const root = temporaryDirectory(t);
  const source = openWorkspace(path.join(root, 'source'));
  const note = createNote(source);
  const sourceContext = createAppContext({ dataStore: source.store, storageRootDir: path.join(root, 'source'), uploadsDir: path.join(root, 'source', 'uploads') });
  const attachment = sourceContext.http.storage.uploadAttachment({ noteId: note.id, fileName: '样本.txt', contentBase64: Buffer.from('附件迁移验证').toString('base64') });
  const snapshot = sourceContext.http.storage.exportKnowledgeBase();
  const sourcePath = path.join(root, 'snapshot.json');
  const bytes = JSON.stringify(snapshot);
  fs.writeFileSync(sourcePath, bytes);
  source.store.close();
  const destination = path.join(root, 'migrated');
  importJsonSnapshot(sourcePath, destination);
  const restored = openWorkspace(destination);
  assert.equal(restored.knowledge.noteService.getNote(note.id).rawMarkdown, '初始正文');
  const targetContext = createAppContext({ dataStore: restored.store, storageRootDir: destination, uploadsDir: path.join(destination, 'uploads') });
  assert.equal(targetContext.http.storage.getAttachmentContent({ id: attachment.id }).content.toString(), '附件迁移验证');
  assert.equal(fs.readFileSync(sourcePath, 'utf8'), bytes);
  restored.store.close();
  assert.throws(() => importJsonSnapshot(sourcePath, destination), /新目录/);
  snapshot.attachmentFiles[0].contentBase64 = Buffer.from('错误文件').toString('base64');
  const invalid = path.join(root, 'invalid.json');
  fs.writeFileSync(invalid, JSON.stringify(snapshot));
  assert.throws(() => importJsonSnapshot(invalid, path.join(root, 'failed')));
  assert.equal(fs.existsSync(path.join(root, 'failed')), false);
});
