import { test } from 'node:test';
import assert from 'node:assert/strict';
import { chromium, expect } from '@playwright/test';
import { createR07Fixture, inspectR07FixtureState } from '../fixtures/ai-r07-runtime.mjs';
import { withPageFailureDiagnostics } from '../fixtures/page-failure-diagnostics.mjs';
for(const driver of ['json','sqlite','postgres'])test(`P2 ${driver} 生产页面：模型计划、明确确认、丢响应重试、撤销与草稿保护`,{skip:driver==='postgres' && !process.env.KNOWRA_SYNC_TEST_DATABASE_URL},async t=>{
  const fixture=await createR07Fixture(driver);let browser;t.after(async()=>{try{await browser?.close();}finally{await fixture.close();}});
  browser=await chromium.launch();const context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await withPageFailureDiagnostics(page, async () => {
  await page.route('**/*',route=>new URL(route.request().url()).origin===fixture.origin?route.continue():route.abort());
  await page.goto(fixture.launchUrl);const headers=driver==='sqlite'?{'X-Knowra-Dataset':(await fixture.store.identity()).datasetId}:{};
  const post=async(path,data)=>{const result=await page.request.post(fixture.origin+path,{headers,data});assert(result.ok(),await result.text());return(await result.json()).data;};
  const space=await post('/api/knowledge/spaces/default',{});await page.goto(`${fixture.origin}/#/assistant?new=1`);
  await expect(page.getByText('离线模拟响应，未调用真实供应商。')).toBeVisible();
  await expect(page.getByRole('button',{name:/本轮用途/})).toHaveCount(0);
  await page.getByRole('textbox',{name:'消息',exact:true}).fill('生成合成笔记');await page.getByRole('button',{name:'发送消息',exact:true}).click();
  await expect(page.getByText('已生成待审成果。请在 AI 成果收件箱继续修改或确认采纳。',{exact:true})).toBeVisible({timeout:15000});
  const actions=(await(await page.request.get(`${fixture.origin}/api/ai/actions?spaceId=${encodeURIComponent(space.id)}`,{headers})).json()).data;
  assert.equal(actions.length,1);const action=actions[0];assert.equal(action.status,'awaitingApproval');
  const notesBefore=(await(await page.request.get(`${fixture.origin}/api/knowledge/notes?spaceId=${encodeURIComponent(space.id)}`,{headers})).json()).data;assert.equal(notesBefore.length,0);
  await page.getByRole('button',{name:'AI 成果收件箱',exact:true}).click();
  const inbox=page.getByRole('complementary',{name:'AI 成果收件箱',exact:true});await inbox.getByRole('button',{name:'审阅成果',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'消息',exact:true})).toBeVisible();
  assert.equal(await page.getByRole('dialog',{name:'AI 成果收件箱',exact:true}).count(),0);
  await page.setViewportSize({width:390,height:843});await expect(inbox).toBeVisible();await expect(page.getByRole('textbox',{name:'消息',exact:true})).toBeHidden();
  await page.setViewportSize({width:1280,height:720});await expect(page.getByRole('textbox',{name:'消息',exact:true})).toBeVisible();
  let lost=true;await page.route('**/api/ai/actions/*/apply',async route=>{const response=await route.fetch();if(lost){lost=false;await route.abort();}else await route.fulfill({response});});
  await inbox.getByRole('button',{name:'确认采纳到笔记',exact:true}).click();await expect(inbox.getByRole('alert')).toBeVisible();
  await inbox.getByRole('button',{name:'查询成果状态',exact:true}).click();await expect(inbox.getByRole('button',{name:'打开正式笔记',exact:true})).toBeVisible();
  await inbox.getByRole('button',{name:'关闭成果',exact:true}).click();
  await page.getByText('执行记录（1）',{exact:true}).click();await page.getByRole('button',{name:'查看计划与结果',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'笔记变更预览',exact:true});await dialog.getByRole('button',{name:'查询执行结果',exact:true}).click();await expect(dialog.getByText('已保存',{exact:true})).toBeVisible();
  await dialog.getByRole('button',{name:'预览撤销',exact:true}).click();await expect(dialog.getByText('合成 AI 记录 · 移入回收站',{exact:true})).toBeVisible();
  await dialog.getByRole('button',{name:'确认并保存',exact:true}).click();await expect(dialog.getByText('已保存',{exact:true})).toBeVisible();
  const saved=await post(`/api/knowledge/notes/${action.plan.items[0].after.id}/restore`,{});assert.equal(saved.deleted,false);
  await dialog.getByRole('button',{name:'关闭',exact:true}).click();
  await page.goto(`${fixture.origin}/#/materials`);await page.reload();
  const index=page.getByRole('article',{name:'笔记索引',exact:true});
  await index.getByRole('button',{name:'合成 AI 记录的笔记操作',exact:true}).click();await page.getByRole('menuitem',{name:'AI 隐私：普通',exact:true}).click();
  const privacy=page.getByRole('dialog',{name:'笔记 AI 隐私',exact:true});await expect(privacy.getByText(/已经发送的内容无法收回/)).toBeVisible();
  await privacy.getByRole('button',{name:'设为私密',exact:true}).click();await expect(privacy).toBeHidden();
  const privateNote=(await(await page.request.get(`${fixture.origin}/api/knowledge/notes/${saved.id}`,{headers})).json()).data;assert.equal(privateNote.aiVisibility,'private');
  await index.getByRole('button',{name:'合成 AI 记录的笔记操作',exact:true}).click();await page.getByRole('menuitem',{name:'AI 隐私：私密',exact:true}).click();
  await privacy.getByRole('button',{name:'设为普通',exact:true}).click();await expect(privacy).toBeHidden();
  await page.goto(`${fixture.origin}/#/assistant`);
  const writeHeaders={...headers,'X-Knowra-AI-Action':'1'};const draft=await page.request.post(`${fixture.origin}/api/ai/actions/drafts`,{headers:writeHeaders,data:{noteId:saved.id,clientId:'synthetic-other-tab',dirty:true}});assert(draft.ok());
  const append=await page.request.post(`${fixture.origin}/api/ai/actions`,{headers:writeHeaders,data:{spaceId:space.id,requestId:'p2-draft-check',toolName:'notes_append',arguments:{noteId:saved.id,rawMarkdown:'不能覆盖草稿'}}});const planned=(await append.json()).data;
  await page.request.post(`${fixture.origin}/api/ai/actions/${planned.actionId}/approve`,{headers:writeHeaders,data:{planHash:planned.plan.planHash}});
  const denied=await page.request.post(`${fixture.origin}/api/ai/actions/${planned.actionId}/apply`,{headers:writeHeaders,data:{}});assert.equal(denied.status(),409);assert.equal((await denied.json()).error.code,'AI_ACTION_DRAFT_CONFLICT');
  await page.reload();await expect(page.getByText('执行记录（3）',{exact:true})).toBeVisible();assert.deepEqual(errors,[]);
  }, () => inspectR07FixtureState(fixture));
});
