import { test } from 'node:test';
import assert from 'node:assert/strict';
import { chromium, expect } from '@playwright/test';
import { createR07Fixture } from '../fixtures/ai-r07-runtime.mjs';
for(const driver of ['json','sqlite','postgres'])test(`P2 ${driver} 生产页面：模型计划、明确确认、丢响应重试、撤销与草稿保护`,{skip:driver==='postgres' && !process.env.KNOWRA_SYNC_TEST_DATABASE_URL},async t=>{
  const fixture=await createR07Fixture(driver);let browser;t.after(async()=>{try{await browser?.close();}finally{await fixture.close();}});
  browser=await chromium.launch();const context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',route=>new URL(route.request().url()).origin===fixture.origin?route.continue():route.abort());
  await page.goto(fixture.launchUrl);const headers=driver==='sqlite'?{'X-Knowra-Dataset':(await fixture.store.identity()).datasetId}:{};
  const post=async(path,data)=>{const result=await page.request.post(fixture.origin+path,{headers,data});assert(result.ok(),await result.text());return(await result.json()).data;};
  const space=await post('/api/knowledge/spaces/default',{});await page.goto(`${fixture.origin}/#/assistant?new=1`);
  await expect(page.getByText('离线模拟响应，未调用真实供应商。')).toBeVisible();
  await page.getByRole('button',{name:/本轮用途/}).click();await page.getByRole('option',{name:'生成新笔记计划',exact:true}).click();
  await page.getByRole('textbox',{name:'消息',exact:true}).fill('生成合成笔记');await page.getByRole('button',{name:'发送消息',exact:true}).click();
  await expect(page.getByText('已生成笔记计划，尚未写入。请在执行记录中查看差异并确认。',{exact:true})).toBeVisible({timeout:15000});
  const actions=(await(await page.request.get(`${fixture.origin}/api/ai/actions?spaceId=${encodeURIComponent(space.id)}`,{headers})).json()).data;
  assert.equal(actions.length,1);const action=actions[0];assert.equal(action.status,'awaitingApproval');
  const notesBefore=(await(await page.request.get(`${fixture.origin}/api/knowledge/notes?spaceId=${encodeURIComponent(space.id)}`,{headers})).json()).data;assert.equal(notesBefore.length,0);
  await page.getByText('执行记录（1）',{exact:true}).click();await page.getByRole('button',{name:'查看计划与结果',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'笔记变更预览',exact:true});await expect(dialog.getByText('合成 AI 记录',{exact:true})).toBeVisible();
  let lost=true;await page.route('**/api/ai/actions/*/apply',async route=>{const response=await route.fetch();if(lost){lost=false;await route.abort();}else await route.fulfill({response});});
  await dialog.getByRole('button',{name:'确认并保存',exact:true}).click();await expect(dialog.getByRole('alert')).toBeVisible();
  await dialog.getByRole('button',{name:'查询执行结果',exact:true}).click();await expect(dialog.getByText('已保存',{exact:true})).toBeVisible();
  await dialog.getByRole('button',{name:'预览撤销',exact:true}).click();await expect(dialog.getByText('合成 AI 记录 · 移入回收站',{exact:true})).toBeVisible();
  await dialog.getByRole('button',{name:'确认并保存',exact:true}).click();await expect(dialog.getByText('已保存',{exact:true})).toBeVisible();
  const saved=await post(`/api/knowledge/notes/${action.plan.items[0].after.id}/restore`,{});assert.equal(saved.deleted,false);
  await dialog.getByRole('button',{name:'关闭',exact:true}).click();
  const writeHeaders={...headers,'X-Knowra-AI-Action':'1'};const draft=await page.request.post(`${fixture.origin}/api/ai/actions/drafts`,{headers:writeHeaders,data:{noteId:saved.id,clientId:'synthetic-other-tab',dirty:true}});assert(draft.ok());
  const append=await page.request.post(`${fixture.origin}/api/ai/actions`,{headers:writeHeaders,data:{spaceId:space.id,requestId:'p2-draft-check',toolName:'notes_append',arguments:{noteId:saved.id,rawMarkdown:'不能覆盖草稿'}}});const planned=(await append.json()).data;
  await page.request.post(`${fixture.origin}/api/ai/actions/${planned.actionId}/approve`,{headers:writeHeaders,data:{planHash:planned.plan.planHash}});
  const denied=await page.request.post(`${fixture.origin}/api/ai/actions/${planned.actionId}/apply`,{headers:writeHeaders,data:{}});assert.equal(denied.status(),409);assert.equal((await denied.json()).error.code,'AI_ACTION_DRAFT_CONFLICT');
  await page.reload();await expect(page.getByText('执行记录（3）',{exact:true})).toBeVisible();assert.deepEqual(errors,[]);
});
