import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
import { chromium, expect } from '@playwright/test';
import { createFileDataStore } from '../../../api/src/infrastructure/file-data-store.js';
import { createAppContext } from '../../../api/src/app.factory.js';
import { createServer } from '../../../api/src/server.js';
import { startLocalRuntime } from '../../src/runtime-server.mjs';

test('真实页面连接云端、后台刷新正文、三份冲突对照与手动合并', { timeout: 60000 }, async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'knowra-sync-ui-'));
  const dataStore = createFileDataStore(path.join(root, 'cloud.json'));
  const cloud = createAppContext({ dataStore, storageRootDir: root, uploadsDir: path.join(root, 'uploads') });
  const space = cloud.modules.knowledge.knowledgeSpaceService.createDefaultKnowledgeSpace({ userId: 'demo' });
  const note = cloud.modules.knowledge.noteService.createNote({ title: '双向同步页面验收', rawMarkdown: '页面共同基线', spaceId: space.id });
  const server = createServer({ appContext: cloud, logger: { error() {} } });
  server.listen(0, '127.0.0.1'); await once(server, 'listening');
  const origin = `http://127.0.0.1:${server.address().port}`;
  const runtime = await startLocalRuntime({ dataDirectory: path.join(root, 'local'), distRoot: fileURLToPath(new URL('../../../web-v4/dist/', import.meta.url)), syncOptions: { autoSync: false } });
  const browser = await chromium.launch({ ...(process.env.V4_BROWSER_CHANNEL === 'chrome' ? { channel: 'chrome' } : {}) });
  t.after(async () => { await browser.close(); await runtime.close(); await new Promise(resolve => server.close(resolve)); fs.rmSync(root, { recursive: true, force: true }); });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage(); const problems = [];
  page.on('pageerror', error => problems.push(error.message));
  await page.goto(runtime.launchUrl);
  await page.getByRole('button', { name: '连接云端', exact: true }).click();
  await page.getByLabel('云端服务地址', { exact: true }).fill(origin);
  await page.getByRole('button', { name: '连接并比较资料', exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('云端已同步');
  await page.getByRole('button', { name: '关闭对话框', exact: true }).click();
  await page.goto(`${runtime.origin}/#/materials/notes/${note.id}`);
  await expect(page.locator('.ProseMirror')).toContainText('页面共同基线');
  // 当前页面保持打开；远端更新后通过同步静默刷新，不需要重新导航。
  cloud.modules.knowledge.noteService.updateNote(note.id, { rawMarkdown: '网页先更新' });
  await page.getByRole('button', { name: '云端已同步', exact: true }).click();
  await page.getByRole('button', { name: '立即同步', exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('云端已同步');
  await page.getByRole('button', { name: '关闭对话框', exact: true }).click();
  await expect(page.locator('.ProseMirror')).toContainText('网页先更新');
  await page.locator('.ProseMirror').click();
  await page.keyboard.press('End'); await page.keyboard.insertText(' 本机保留的段落');
  await expect(page.getByRole('contentinfo')).toContainText('已保存到本机');
  cloud.modules.knowledge.noteService.updateNote(note.id, { rawMarkdown: '云端并发的段落' });
  await page.getByRole('contentinfo').getByRole('button', { name: /待同步|云端已同步/ }).click();
  await page.getByRole('button', { name: '立即同步', exact: true }).click();
  const conflict = page.getByRole('region', { name: '冲突：双向同步页面验收' });
  await expect(conflict).toContainText('本机保留的段落');
  await expect(conflict).toContainText('云端并发的段落');
  await conflict.getByText('查看共同基线', { exact: true }).click();
  await expect(conflict).toContainText('网页先更新');
  const screenshots = process.env.KNOWRA_E2E_OUTPUT;
  if (screenshots) { fs.mkdirSync(screenshots, { recursive: true }); await page.screenshot({ path: path.join(screenshots, 'sync-conflict.png') }); }
  await conflict.getByRole('button', { name: '手动合并', exact: true }).click();
  await conflict.getByLabel('合并后的正文', { exact: false }).fill('手动合并：保留本机和云端两段');
  await conflict.getByRole('button', { name: '保存合并结果', exact: true }).click();
  await expect(conflict).toHaveCount(0);
  await page.getByRole('button', { name: '关闭对话框', exact: true }).click();
  await expect(page.locator('.ProseMirror')).toContainText('手动合并：保留本机和云端两段');
  assert.equal(cloud.modules.knowledge.noteService.getNote(note.id).rawMarkdown, '手动合并：保留本机和云端两段');
  const versions = (await (await context.request.get(`${runtime.origin}/api/knowledge/notes/${note.id}/versions`)).json()).data;
  assert.equal(new Set(versions.map(version => version.contentHash)).size, versions.length);
  assert.deepEqual(problems, []);
  if (screenshots) await page.screenshot({ path: path.join(screenshots, 'sync-resolved.png') });
});
